# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkvbot < Formula
  desc "Automation for makemkv"
  homepage "github.com/curt-hash/mkvbot"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/curt-hash/mkvbot/releases/download/v0.1.0/mkvbot_Darwin_x86_64.tar.gz"
      sha256 "be5107f1903f3654c3a0672c01685ba628e0626e96786918d3fc200b3a4614d0"

      def install
        bin.install "mkvbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/curt-hash/mkvbot/releases/download/v0.1.0/mkvbot_Darwin_arm64.tar.gz"
      sha256 "420dea565dd09550942c16779ead627ac042599c459e104ae04b9136e9071a3a"

      def install
        bin.install "mkvbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curt-hash/mkvbot/releases/download/v0.1.0/mkvbot_Linux_x86_64.tar.gz"
        sha256 "c3bffaceb61cd12252d939a14896237290313e0af32a12bb6bba32f390c6cd03"

        def install
          bin.install "mkvbot"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curt-hash/mkvbot/releases/download/v0.1.0/mkvbot_Linux_arm64.tar.gz"
        sha256 "d9ed5712d0a76ba962a53a9bd7248df15e6fab918ad966536c8821b152280baf"

        def install
          bin.install "mkvbot"
        end
      end
    end
  end

  test do
    system "#{bin}/mkvbot -v"
  end
end
