# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkvbot" do
  name "mkvbot"
  desc "Automation for makemkv"
  homepage "https://github.com/curt-hash/mkvbot"
  version "0.5.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkvbot"

  on_macos do
    on_intel do
      url "https://github.com/curt-hash/mkvbot/releases/download/v#{version}/mkvbot_Darwin_x86_64.tar.gz"
      sha256 "53a72ba631808cdc216e6ff559d3e5747effc5c6cbb705cb9a7c70d923c4383c"
    end
    on_arm do
      url "https://github.com/curt-hash/mkvbot/releases/download/v#{version}/mkvbot_Darwin_arm64.tar.gz"
      sha256 "09eb163adc6d2aeae8a6871312bebd63279b034ccad28b56a25a18ac1f626f7f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/curt-hash/mkvbot/releases/download/v#{version}/mkvbot_Linux_x86_64.tar.gz"
      sha256 "df1c16b3b24ee8c0d37a8616f524b968618b6b7b3a6feeb1a356b680e76e5e5b"
    end
    on_arm do
      url "https://github.com/curt-hash/mkvbot/releases/download/v#{version}/mkvbot_Linux_arm64.tar.gz"
      sha256 "b0067cbad679f06cdd703fd4a1634e89872fc758f9dbe1c204e16e40b07e87b4"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mkvbot"]
    end
  end

  # No zap stanza required
end
