# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkvbot" do
  desc "Automation for makemkv"
  homepage "https://github.com/curt-hash/mkvbot"
  version "0.5.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkvbot"

  on_macos do
    on_intel do
      url "https://github.com/curt-hash/mkvbot/releases/download/v0.5.5/mkvbot_Darwin_x86_64.tar.gz"
      sha256 "b879e5de13bbb143a147a7e0851f5dea8e3be10ea70119ea10a977bfd5f5045f"
    end
    on_arm do
      url "https://github.com/curt-hash/mkvbot/releases/download/v0.5.5/mkvbot_Darwin_arm64.tar.gz"
      sha256 "529b9025c0c1db8aeb750fdb0ef2737311500f145cc7f7c03c728df08af1d423"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/curt-hash/mkvbot/releases/download/v0.5.5/mkvbot_Linux_x86_64.tar.gz"
      sha256 "eaf4c774329ab6ae336844fbc279725e83ad6c15788a0a0dc6bece1fba0b23d5"
    end
    on_arm do
      url "https://github.com/curt-hash/mkvbot/releases/download/v0.5.5/mkvbot_Linux_arm64.tar.gz"
      sha256 "be9f498e1ba2a2542ce22c1d78a6348e6c83c425516f6e174e430d33dd1afdf7"
    end
  end

  conflicts_with formula: [
      "mkvbot",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mkvbot"]
    end
  end

  # No zap stanza required
end
