# This file was generated by GoReleaser. DO NOT EDIT.
cask "mkvbot" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "a72d7038594710a13624c955104ad9831bb73801fbae9bc63d118147270417d4"
      url "https://github.com/curt-hash/mkvbot/releases/download/v#{version}/mkvbot_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6589cf7299574430904f35a443fa2d46ffdbdf7c6f872a7961542a1e70c7c58e"
      url "https://github.com/curt-hash/mkvbot/releases/download/v#{version}/mkvbot_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5c34454e5491b196ed454befd39bb90fa7ff4d3ca2802396c4160cac9c4ed857"
      url "https://github.com/curt-hash/mkvbot/releases/download/v#{version}/mkvbot_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "573c7b87f7154aef766b7a584843ac8ad83b3d5dee19db320252d4ac40ba0bae"
      url "https://github.com/curt-hash/mkvbot/releases/download/v#{version}/mkvbot_Linux_arm64.tar.gz"
    end
  end

  name "mkvbot"
  desc "Automation for makemkv"
  homepage "https://github.com/curt-hash/mkvbot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mkvbot"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mkvbot"]
    end
  end

  # No zap stanza required

end
