# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkvbot < Formula
  desc "Automation for makemkv"
  homepage "https://github.com/curt-hash/mkvbot"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/curt-hash/mkvbot/releases/download/v0.3.0/mkvbot_Darwin_x86_64.tar.gz"
      sha256 "8358de18a7467c69d7e21b73a89eadc02dcf2ebbc883399e68812f467ffc0008"

      def install
        bin.install "mkvbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/curt-hash/mkvbot/releases/download/v0.3.0/mkvbot_Darwin_arm64.tar.gz"
      sha256 "90b1f3db8676a0a23e8528007a12f854485f9b8b436b7cee4ca4beabb94c5cb7"

      def install
        bin.install "mkvbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curt-hash/mkvbot/releases/download/v0.3.0/mkvbot_Linux_x86_64.tar.gz"
        sha256 "b5c27d46dbec14f9fcc3c21d9c286e2b0d56adf94916b55bc8de2f7866cfcfc1"

        def install
          bin.install "mkvbot"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curt-hash/mkvbot/releases/download/v0.3.0/mkvbot_Linux_arm64.tar.gz"
        sha256 "13b02379bffbae88100883567ac5368105ce04d3bc026eea2aa965180731fd06"

        def install
          bin.install "mkvbot"
        end
      end
    end
  end

  test do
    system "#{bin}/mkvbot", "-v"
  end
end
