# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mkvbot < Formula
  desc "Automation for makemkv"
  homepage "https://github.com/curt-hash/mkvbot"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/curt-hash/mkvbot/releases/download/v0.1.1/mkvbot_Darwin_x86_64.tar.gz"
      sha256 "5d11482db1ca85ee3131214574cd2463f4d44c185d09eb87bfe4b3dbb172b7c0"

      def install
        bin.install "mkvbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/curt-hash/mkvbot/releases/download/v0.1.1/mkvbot_Darwin_arm64.tar.gz"
      sha256 "9271d9aa076b9b2529efc5dcb1e914ebd6f09ea283f7a4b4f365ecbb91270add"

      def install
        bin.install "mkvbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curt-hash/mkvbot/releases/download/v0.1.1/mkvbot_Linux_x86_64.tar.gz"
        sha256 "87a7c675e97bece6ddd2173db6fff36d0e90987638b4a5822655a3c838c4453b"

        def install
          bin.install "mkvbot"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/curt-hash/mkvbot/releases/download/v0.1.1/mkvbot_Linux_arm64.tar.gz"
        sha256 "69e91c80935003ac7a549997bcdfe8f3898c69cd68c16573651ea3fa568147ea"

        def install
          bin.install "mkvbot"
        end
      end
    end
  end

  test do
    system "#{bin}/mkvbot", "-v"
  end
end
